### PR TITLE
Model View Controller Pattern

### LINKED ISSUE #307: ACARS Confirm Details
**Is your feature request related to a problem? Please describe.**
Many of the details that the ACARS gathers are never presented to us.

**Describe the solution you'd like**
I'd like an additional prompt after you input your flight nr and fuel where all the flight details are presented at which point one could confirm or edit some of the details.

**Describe alternatives you've considered**
There's not really much.

### LINKED ISSUE #317: Theming
Flare has always made customization a priority. From day one, the colors of Flare have been changeable. But we've now reached a point where Flare's design has run it's course, at least for some people. Theming will give VAs the ability to completely customize how their Crew Center looks using a beautiful range of themes built by Flare Developers and the community.

The development team are also considering adding an option to allow users to choose their own theme.

### PR DESCRIPTION
**Pull request by velocity23**
## Description

This pull request adds the MVC structure required for theming.

Closes #317
Closes #307 

## Changes

Too many to list

### CODE REVIEW

**Comment by velocity23** [comment]
I've just realized the `vanet.php` file should be part of the default theme, don't merge just yet

**Comment by velocity23** [comment]
Also aware that plugins no longer exist after this PR, but that's something I'll work on at a later date

**Comment by velocity23** [comment]
Fixed vanet.php issue, will work on plugins at a later date - they're going to need a rethink and possibly rebuild on the plugin side

**Comment by velocity23** [comment]
Ready for your review @rebal15

**Review by rebal15 — APPROVED** [review]
All good - I skimmed through most of it, and had a proper read of the core files/base classes, got a good idea of how everything is fitting together, awesome work 😆😍

**Pull request merged**
